### ISSUE TITLE
Initiate package review request

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/covizpy#100]
Open issue at https://github.com/UBC-MDS/software-review-2022 to initiate package review request. For initiating a reviewing request in Python, use the template under Submit Software for Review at [this link](https://github.com/pyOpenSci/software-review/blob/main/.github/ISSUE_TEMPLATE/submit-software-for-review.md).

**Comment by lirnish** [comment]
The issue was opened here:
https://github.com/UBC-MDS/software-review-2022/issues/51#issue-1121602901
