### ISSUE TITLE
[Discuss] License Choice

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/covizpy#101]
Discuss and reason the license choice by opening issues in both repositories

**Comment by ytz** [comment]
Hi all,

Currently we are using the MIT License for both `covizpy` and `covizr`. As stated by https://choosealicense.com/, 
>  The [MIT License](https://choosealicense.com/licenses/mit/) is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions.

Reason for using MIT License:
- We want a simple license that is accessible to everyone, and spread the use of existing research and data
- Can be used and modified by future MDS students for learning purposes
- Do not want to be held liable or provide warranty

Let me know if you have other points to add here!

**Comment by thomassiu** [comment]
Hi TZ,

Thank you very much and I have no further comment.

**Comment by lirnish** [comment]
Thanks TZ and Thomas, I also agree MIT license is a suitable license for us, as it is commonly used and permissive, which encourages others to use our package or modify it.

**Comment by rrrohit1** [comment]
Thank you everyone for the comments. I agree with the points mentioned above for the choice of license. It enables users to reproduce and share their work easily which is in line with our package's functionalities.
