### ISSUE TITLE
Task of Week 2

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/covizpy#14]
Summary of Week 2 tasks

Milestone Checklist:

Function specific:
- [x] Writing code for each function
- [x] Handle incorrect input and errors with useful error messages
- [x] Writing unit test function for each function (test_function_name.py in tests/ folder, 3-5 edge cases, with documentation, make sure that the tests cover all branches)
- [x] use pytest to check test and code coverage

Overall:
- [x] Manage issues: Project boards & Milestones: Create an issue for each function, add tasks, assign people to each issue
- [x] Use poetry add to add the dependency (e.g., poetry add --dev pytest, poetry add <dependency>) and update README to reflect that
- [x] Update usage section on README, make sure the Python package functions can be installed and used from GitHub
- [x] Submit on canvas. URL of repo + URL of release

Let me know if I missed anything.

**Comment by rrrohit1** [comment]
Are we writing different test py scripts for different functions?

**Comment by thomassiu** [comment]
> Are we writing different test py scripts for different functions?

Yes, we can make one test py for each of our function for easier management.
