### ISSUE TITLE
Tasks for Week 1

### ISSUE THREAD

**Issue by rrrohit1** [UBC-MDS/covizpy#2]
Summary of points discussed in lab + week 1 tasks

Milestone Checklist:

- [x] Teamwork Contract: Submit to Canvas
- [x] Pick a topic: Covid Dataset EDA
- [x] Project Structure: Create repo
- [x] Project Structure: Add contributor names
- [x]  Project Structure: Update README with summary para, functions, etc.
- [x] Function specifications: complete docstrings
- [x] Manage issues: Project boards & Milestones: Create issue for each function, add tasks, assign people to each issue
- [x] Other stuff: Commit regularly, meaningful commits. Create a branch -> Work on function -> Commit -> Open Pull Reuqest -> Wait for code review -> After addressing feedback, the expectation is that one of them(other team members) merges the PR.
- [x] Submit on canvas. URL of repo + URL of release + Contract

The first three tasks are done. The function specifications task will be done individually for every function and the second last point is expected to be done by everyone. The last point of submission will be done by the Proof-reader itself.

So, we are left with three other tasks: task 4 and 5 related to Project Structure and task 7 related to setting up Project Board and Milestones.

I can volunteer to do task 7 if everyone agrees. 

Someone else has to update REAMDE+CONTRIBUTING (task 4+5). Feel free to discuss it in this issue. Let me know if I missed anything.

**Comment by ytz** [comment]
Thanks @rrrohit1. I can try to write something for `README` first. Meanwhile let's try to specify what functions we want to do soon (I'm still trying to think of one lol)

**Comment by thomassiu** [comment]
@rrrohit1 and all, I will create the project board and pre-set milestones label tonight.

**Comment by lirnish** [comment]
@rrrohit1 by update CONTRIBUTING do you mean CONTRIBUTING.md? I looked at the milestone 1 requirement and seems like we could use the default version, is there anything specific you feel like we should update? 
After we set our function names, I could update README with specific functions, etc.

**Comment by rrrohit1** [comment]
@lirnish Sorry. I meant adding our names to the CONTRIBUTING section of README. Nothing more. @ytz has done it already.

Any changes you make in the README going forward, do it in your branch and then merge it. Thanks!

**Comment by thomassiu** [comment]
Created the project board and moved milestone 1 issues to TODO.
