### ISSUE TITLE
Alignment of default date

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#20]
Hi,

As our functions have a default date range (date_from, date_to), please suggest the default value so we can align.
At the moment the get_data function uses D-7 to D. If needed I can change so that all functions can be streamlined and re-used.

**Comment by lirnish** [comment]
I have no preference about this, I am ok if we changed to D-7.
Related to this, when I am looking at your documentation I feel like '%Y-%m-%d' is not very intuitive... I need to search online in order to confirm what is the exact format, could we add an example, like "2021-12-31"?

**Comment by thomassiu** [comment]
Hi Rohit,

Thanks - I'll change to a more intuitive format, i,.e, '2021-12-31'

Thomas

**Comment by ytz** [comment]
Yea I'm also ok with D-7 to D

**Comment by lirnish** [comment]
> Hi Rohit,
> 
> Thanks - I'll change to a more intuitive format, i,.e, '2021-12-31'
> 
> Thomas

Sounds good thanks! BTW, I am Rong lol

**Comment by thomassiu** [comment]
Closing this issue as we have made an alignment =)
