### ISSUE TITLE
Checklist for package runs/tests

### ISSUE THREAD

**Issue by rrrohit1** [UBC-MDS/covizpy#27]
Hey team. Try running the function in the package environment and see if the function runs successfully or not. Then kindly check the boxes below after it runs successfully.

Creating package env:
`conda create --name covizpy python=3.9 -y`

Check func output:
- [x] get_data
- [x] plot_metric
- [x] plot_spec
- [x] plot_summary

Check func tests:
`pytest tests/plot_metric`

- [x] get_data
- [x] plot_metric
- [x] plot_spec
- [x] plot_summary

To view the plot from the terminal, use the code given below:

`import altair_viewer
plot_metric().show() `

After the above are done successfully, we will put a PoetryLock. We need to ensure that the package installs successfully from Github in this milestone by running the below code.

`pip install git+[url here]`

Thank you!

**Comment by thomassiu** [comment]
To clarify, after we created a new conda environment, we run `poetry install` in the project directory to install the package?

**Comment by ytz** [comment]
> To clarify, after we created a new conda environment, we run poetry install in the project directory to install the package?

Yes

**Comment by ytz** [comment]
Noticed my test broke due to changes in dataset. I have now referenced my test to a pickle file instead of `get_data` directly. See #29

**Comment by thomassiu** [comment]
closing this issue as all checks were done.
