### ISSUE TITLE
Authors in each script

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#28]
Hi all,

Shall we also add the author to the .py files we write?

**Comment by ytz** [comment]
Sure. Maybe it will help the TA with the marking. Maybe something simple like:
```
# File Name: plot_summary.py
# Author: TZ Yan
```
at the top of the file

**Comment by thomassiu** [comment]
Updated functions get_data and test_get_data with above information.

**Comment by rrrohit1** [comment]
Updated in plot_metric and test_plot_metric

**Comment by thomassiu** [comment]
Closing this issue since all files have been updated
