### ISSUE TITLE
Note that the original dataset "location" has "World" "Asian" "Lower middle income" etc.

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/covizpy#40]
Note that the original dataset "location" includes "World" "Asian" "Lower middle income" etc.

I noticed @ytz in his function plot_summary has removed those rows by `df = df[~df["iso_code"].str.startswith("OWID")]`, so his result seems fine.
But the summary in plot_metric is not really the daily COVID cases @rrrohit1 

What about get_data()? Should those rows be removed there too? Or we may change the description of "location" so it includes that? @thomassiu

**Comment by thomassiu** [comment]
Hi Rong, get_data() has updated this filtering as part of #38

**Comment by rrrohit1** [comment]
@thomassiu Thanks a lot! I won't be modifying my code then.

**Comment by thomassiu** [comment]
@lirnish please check with the lastest code and see if the dataset looks fine now, thanks!

**Comment by lirnish** [comment]
@rrrohit1 I don't think get_data() function fix yours cuz you are not using df right?  The data you downloaded will still have those columns

**Comment by rrrohit1** [comment]
I am fetching the data using get_data(). Should be fine.

**Comment by lirnish** [comment]
got it, that make sense
