### ISSUE TITLE
You may want to fix this

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/covizpy#41]
Hi @rrrohit1
The pytest consistently failed on my PC and I think it is probably because of the data server you imported, so I add that to the dependency list and now is good.

Meanwhile, I feel like your tests look weird to me, e.g., for the first assertion in the second function:
`assert plot_metric().layer[1].mark.type, 'line'`
This does pass, however, the following also pass:
`assert plot_metric().layer[1].mark.type, 'not a line'`
It feels like it is not comparing the result and the string you put, but just `assert True, "some optional message if the test failed"`

So I think you may want to modify those to something like:
`assert plot_metric().layer[1].mark.type == 'line', "some optional message if the test failed"`

Another thing is, the milestone 2 Exception handling says: "it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages". And I noticed while trying the first function is that you actually return the error message not raise it, not sure if that is a problem or not.

**Comment by rrrohit1** [comment]
Hey. I was contemplating between raising and returning the messages. Thanks for pointing these. I've made all the changes in the function and the tests as well. These should reflect in the next PR. Thanks!
