### ISSUE TITLE
test_plot_metric not passing one assert

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#45]
@rrrohit1 I just ran the `poetry run pytest` from the code in main branch and found the following error:

FAILED tests/test_plot_metric.py::test_plot_metric_input - Failed: DID NOT RAISE <class 'TypeError'>

I tried running the code `plot_metric(date_from=123)` and it only returns a message instead of error. Can you please check?

**Comment by thomassiu** [comment]
hold on, looks like I didn't pull the latest one and my code has some other issue too ...

**Comment by rrrohit1** [comment]
Runs fine in locally. The latest one.

**Comment by thomassiu** [comment]
yep, just checked again after re-installing it.
