### ISSUE TITLE
Final run of the package

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#51]
Hi all,

Please use the following commands to try out the package installation:

`conda create --name coviztest python=3.9 -y`
`conda activate coviztest`
`pip install pandas altair altair_saver`
`pip uninstall covizpy` <- to ensure there isn't a covizpy package
`pip install --index-url https://test.pypi.org/simple/ covizpy`

Then use python to perform sanity checks there, thanks! It should install covizpy v1.0.0

**Comment by rrrohit1** [comment]
Checked all the functions with outputs and with some invalid inputs for checking exception/error handling. Everything looks good. Thanks for listing the command list above.

**Comment by thomassiu** [comment]
Thanks! closing this issue.
