### ISSUE TITLE
Check ci-cd.yml and workflow

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#58]
Here are the checks on ci-cd.yml. Most of them should be there and for action that currently fails, it requires to install sphinx on the poetry dev.

Overall:
- [x] Workflow in `.github/workflows/ci-di.yml` is correctly configured so that it does the following while pushes and pulling to the project's deployment branch (e.g. main)
- [x] Runs the test suite
- [x] Style checkers
- [x] **Deploy to TestpyPI** 
- [x] It should be evidenced by a green release button on the package repository's README
- [x] Ensure deployment branch (e.g. main branch) is correctly specified on lines 6, 9, 42
- [x] Ensure correct Python version is listed on line 19 (should match with `pyproject.toml`)

**Comment by thomassiu** [comment]
Hi @lirnish ,

Just checked the latest version of the branch protection bot git repo, they changed the parameter access-token into access_token (https://github.com/benjefferies/branch-protection-bot).

Can you update the ci-cd yaml and try again? thanks!

**Comment by lirnish** [comment]
Thanks @thomassiu ! Let me do a pull request again

**Comment by lirnish** [comment]
It seems like even after the fix the deactivate of the branch protection is not working...

**Comment by thomassiu** [comment]
I see one of our classmates also asked the same in Slack. Also Tiff was doing tests too on her repo and with the same result (https://github.com/ttimbers/pycounts_tat). So I'm trying something else too ...

**Comment by lirnish** [comment]
hmm ok, if nothing works, we could maybe just disable branch protection...

**Comment by lirnish** [comment]
seems still not working @thomassiu and getting a same error message, and did Tiff said she was doing tests on slack? I couldn't find it

**Comment by thomassiu** [comment]
She didn't say but I found she was testing 😆

**Comment by thomassiu** [comment]
I am testing it via my own project repository, quite some changes has to be made to make it work. At least now I can create a release! Just need to test publishing to testpypi and pypi...

**Comment by thomassiu** [comment]
I made it working!!!
Check my cicd and the actions there... 

https://github.com/thomassiu/pycounts/blob/main/.github/workflows/ci-cd.yml

**Comment by thomassiu** [comment]
Changes I have made:

In ci:
Added Check style (step 6)

In cd:
Added Step 4 Install poetry
Replace original "Use PSR..." into the one "Bump version and tagging..."
Added Step 8. Build package

Note 1: The step numbers were not fully ordered.
Note 2: I decided to add back the conditions at the top, otherwise there will be a lot of redundant checks
Note 3: in step 10, change back to covizpy when you wanna copy this...

**Comment by thomassiu** [comment]
I have also added git push after poetry version in CD step 6 to make sure pyproject.toml version bump has updated to the repo.

**Comment by thomassiu** [comment]
@lirnish  and all, tests completed at my repo and you may use the version here... 
https://github.com/thomassiu/pycounts/blob/main/.github/workflows/ci-cd.yml

**Comment by lirnish** [comment]
Wow awesome!! Thank you @thomassiu !!! I will update it now

**Comment by thomassiu** [comment]
all fixed and closed by #78
