### ISSUE TITLE
cd failed at Python Semantic Release

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/covizpy#65]
Looks like the recent PR failed when merging to main. See https://github.com/UBC-MDS/covizpy/runs/4962891724?check_suite_focus=true

Not sure if this is due to the previous step to disable admin branch protection. Any ideas?

**Comment by thomassiu** [comment]
Seems the command of semantic uses a role that is not an administrator. Thus I have just added to use an admin token (generated by Rong) in the latest PR #63 . Similar discussion at #58

**Comment by rrrohit1** [comment]
Is this due to the branch protection option being active?

**Comment by rrrohit1** [comment]
We can try removing the below rule. My guess is that it disallows the removing branch protection without an approval.

`At least 1 approving review is required by reviewers with write access.`

**Comment by thomassiu** [comment]
Worse case is to just remove it and let the original cicd workflow run. I've been testing it whole morning and hopefully I found a way to work =D

**Comment by thomassiu** [comment]
It works now in my own repo~

https://github.com/thomassiu/pycounts/blob/main/.github/workflows/ci-cd.yml

**Comment by thomassiu** [comment]
fixed as part of #72
