### ISSUE TITLE
Style checks

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#68]
Hi all,

To enable auto-style formatting in visual studio (I'm using black)

https://dev.to/adamlombard/how-to-use-the-black-python-code-formatter-in-vscode-3lo0

Afterwards, you can format the files manually using:
`poetry run black src/`
`poetry run black tests/`

Thereafter, all new changes should be formatted automatically.

Then, to incorporate with our workflow on git, also execute the following to ensure it won't break during CICD check:

`poetry run flake8 --exclude=docs* --max-line-length 120`

This line can be added in our cici.yml later on.

**Comment by thomassiu** [comment]
Here are a snapshot of files to fix - can each of us fix the corresponding file? I will cater the __init__ and test_covizpy

/src/covizpy/plot_metric.py:8:1: E302 expected 2 blank lines, found 1
./src/covizpy/plot_metric.py:12:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:16:79: W291 trailing whitespace
./src/covizpy/plot_metric.py:23:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:28:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:33:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:47:30: W291 trailing whitespace
./src/covizpy/plot_metric.py:49:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:54:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:55:5: E303 too many blank lines (2)
./src/covizpy/plot_metric.py:56:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:64:74: E203 whitespace before ','
./src/covizpy/plot_metric.py:65:37: E128 continuation line under-indented for visual indent
./src/covizpy/plot_metric.py:66:1: W293 blank line contains whitespace
./src/covizpy/plot_metric.py:70:69: E203 whitespace before ','
./src/covizpy/plot_metric.py:71:37: E128 continuation line under-indented for visual indent
./src/covizpy/plot_metric.py:74:28: E251 unexpected spaces around keyword / parameter equals
./src/covizpy/plot_spec.py:32:76: W291 trailing whitespace
./src/covizpy/plot_spec.py:44:1: W293 blank line contains whitespace
./src/covizpy/plot_spec.py:48:1: W293 blank line contains whitespace
./src/covizpy/plot_spec.py:145:16: W292 no newline at end of file
./src/covizpy/__init__.py:3:33: W292 no newline at end of file
./src/covizpy/get_data.py:95:5: E722 do not use bare 'except'
./tests/test_plot_metric.py:5:1: F401 'pytest.fixture' imported but unused
./tests/test_plot_metric.py:7:1: E302 expected 2 blank lines, found 1
./tests/test_plot_metric.py:22:1: W293 blank line contains whitespace
./tests/test_plot_metric.py:29:6: E114 indentation is not a multiple of 4 (comment)
./tests/test_plot_metric.py:29:6: E116 unexpected indentation (comment)
./tests/test_plot_metric.py:34:1: W293 blank line contains whitespace
./tests/test_covizpy.py:1:1: F401 'covizpy.covizpy' imported but unused
./tests/test_get_data.py:32:4: E114 indentation is not a multiple of 4 (comment)
./tests/test_plot_spec.py:5:1: F401 'covizpy.get_data.get_data' imported but unused
./tests/test_plot_spec.py:6:1: F401 'pandas as pd' imported but unused
./tests/test_plot_spec.py:28:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:43:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:48:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:53:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:58:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:63:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:68:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:81:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:84:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:87:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:89:61: E225 missing whitespace around operator
./tests/test_plot_spec.py:90:1: W293 blank line contains whitespace
./tests/test_plot_spec.py:92:154: W292 no newline at end of file
./tests/test_plot_summary.py:2:1: F401 'covizpy.get_data.get_data' imported but unused
./tests/test_plot_summary.py:3:1: F401 'pandas as pd' imported but unused

**Comment by lirnish** [comment]
@ytz @rrrohit1 
I am fixing mine and run the test again, and I still see these three errors, do you mind fix the file? Or let me know if you are ok with me deleting those imports. Thanks
./tests/test_plot_metric.py:5:1: F401 'pytest.fixture' imported but unused
./tests/test_plot_summary.py:2:1: F401 'covizpy.get_data.get_data' imported but unused
./tests/test_plot_summary.py:3:1: F401 'pandas as pd' imported but unused

**Comment by rrrohit1** [comment]
Ya. You can delete it.

**Comment by ytz** [comment]
Yea can delete mine as well, thanks

**Comment by thomassiu** [comment]
all fixed and verified by #78
