### ISSUE TITLE
Limit cicd workflow for tags creation

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#80]
Hi @lirnish ,

Can you update the cicd.yml header to this - it will limit redundant workflow triggered when a new tag is created (see our Actions history and you will see there are some called ci-cd which is not needed). I tested on my repo that all other PRs, commits from other branches will still trigger the workflows.

```block
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
```

**Comment by lirnish** [comment]
ok
