### ISSUE TITLE
Add links to pyproject

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/covizpy#84]
As per requirement in lecture 6 notes, we need to add the following to pyproject.toml:

[tool.poetry] 
readme = "README.md"
homepage = "https://github.com/UBC-MDS/covizpy"
repository = "https://github.com/UBC-MDS/covizpy"
documentation = 'https://covizpy.readthedocs.io'

can someone help to update it (note that we also need to update the version number matching the current tag)? coz I have committed too much already =P

**Comment by lirnish** [comment]
I could do the adding, btw, what version number you are tallking about? the toml file version number will auto update I think?

**Comment by thomassiu** [comment]
yes it will be auto update, but if your version in local is not pulled then
it might be outdated lol

**Comment by thomassiu** [comment]
closed by #85
