### ISSUE TITLE
Package icon?

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/covizpy#86]
Thought it will be more fun to include a package icon. I just slapped a few emojis on a hexagon, any thoughts?
<img width="253" alt="Screen Shot 2022-01-28 at 1 53 22 PM" src="https://user-images.githubusercontent.com/1884616/151627158-3e933929-009a-4309-91e1-280dd79dd743.png">

**Comment by lirnish** [comment]
lol look nice, how could include that?

**Comment by ytz** [comment]
Oh, I was just thinking of adding it in the README.md.

**Comment by thomassiu** [comment]
haha good idea! put it to readme lol!

**Comment by rrrohit1** [comment]
:joy: nice
